tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "maaassistantarknights/tap"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Simple, fast and user-friendly alternative to find
brew "fd"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Tools for zmodem/xmodem/ymodem file transfer
brew "lrzsz"
# Powerful, lightweight programming language
brew "lua"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Development kit for the Java programming language
brew "openjdk@11"
# SSL/TLS VPN implementing OSI layer 2 or 3 secure network extension
brew "openvpn"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Tool for managing OCI containers and pods
brew "podman"
# Generic machine emulator and virtualizer
brew "qemu"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# Audio utility
cask "background-music"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-sauce-code-pro-nerd-font"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Archive manager for data compression and backups
cask "rar"
# Rime input method engine
cask "squirrel"
# System monitor for the menu bar
cask "stats"
# Free and open-source OpenVPN client
cask "tunnelblick"
